# Setup
title:               Vahan Aghajanyan
tagline:             'The Blog'
description:         'I am <a href= "mailto:vahancho@gmail.com">Vahan Aghajanyan</a>, a software developer in Hamburg, Germany. <a href= "https://vahancho.github.io/about/">More about me.</a>'
url:                 https://vahancho.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

github:
  repo: https://github.com/vahancho?tab=repositories

# About/contact
author:
  name:              Vahan Aghajanyan
  url:               www.linkedin.com/in/vahancho
  email:             v...o@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: G-EQ2ZN30TYJ
